# losslessbob_backend.spec
# Backend-only onefile build — bundled as a resource inside the Electron AppImage.
# Run: pyinstaller losslessbob_backend.spec

block_cipher = None

a = Analysis(
    ['run_backend.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'flask',
        'flask_cors',
        'werkzeug',
        'werkzeug.serving',
        'werkzeug.debug',
        'lxml',
        'lxml.etree',
        'lxml._elementpath',
        'bs4',
        'bs4.builder._lxml',
        'bs4.builder._htmlparser',
        'waitress',
        'waitress.task',
        'waitress.server',
        'watchdog',
        'watchdog.observers',
        'watchdog.observers.inotify',
        'requests',
        'urllib3',
        'charset_normalizer',
        'certifi',
        'sqlite3',
        '_sqlite3',
        'numpy',
        'scipy',
        'scipy.signal',
        'scipy.fft',
        'scipy.ndimage',
        'librosa',
        'librosa.core',
        'soundfile',
        'numba',
        'llvmlite',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'pandas',
        'cv2',
        'PyQt6',
        'test',
        'unittest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='LosslessBobBackend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
