#!/usr/bin/env python3
"""fn_label_census.py — objective label-error heuristic census over the FN population.

Report-only companion to ``audit_fn.py``: derives the same corr<0.05
false-negative population (frozen-set positives the current committed
``config.yaml`` still verdicts ``different_family``), via
``audit_fn._current_fn_population`` — the exact machinery ``audit_fn.py``
uses — and re-applies exactly 2 of its objective ``label_assessment``
heuristics (reused unmodified from ``audit_fn.py``):

  (a) ``_explicit_different_recording`` — curator relation/source text
      directly asserts the two LBs are a different recording.
  (b) ``_duration_mismatch`` — speed-corrected performance-duration ratio
      is >15% off unity (different length/setlist).

Unlike ``audit_fn.py`` this script performs **zero DB writes** (no schema
migration, no ``label_suspect`` flagging, no ``pairs`` UPDATE) and **zero
label edits** — it opens the observations DB read-only via
``regression._connect`` and only ever executes SELECTs. It scans the full
FN population rather than a stratified sample, and skips the taper-conflict
heuristic and the audio-based envelope quick check (both excluded by task
scope).

Usage:
    .venv/bin/python3 tools/tapematch/fn_label_census.py
"""
from __future__ import annotations

import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

import audit_fn as AF  # noqa: E402
import regression as R  # noqa: E402

HEURISTIC_A = "explicit_different_recording"
HEURISTIC_B = "duration_mismatch_15pct"


def _scan(conn) -> tuple[list[dict], list[dict]]:
    """Return (fn_rows, hits) — the full FN population and the heuristic hits.

    Each ``hits`` entry is a dict: ``concert_date``, ``lb_a``, ``lb_b``,
    ``heuristics`` (list of heuristic names that fired for this pair), and
    ``evidence`` (dict heuristic name -> one-line snippet).
    """
    _frozen, fn_rows = AF._current_fn_population(conn)

    hits: list[dict] = []
    for row in fn_rows:
        text_a = AF._source_text(conn, row["run_id"], row["concert_date"], row["lb_a"])
        text_b = AF._source_text(conn, row["run_id"], row["concert_date"], row["lb_b"])

        fired: list[str] = []
        evidence: dict[str, str] = {}

        diff_hit, diff_snip = AF._explicit_different_recording(row, text_a, text_b)
        if diff_hit:
            fired.append(HEURISTIC_A)
            evidence[HEURISTIC_A] = f'"{diff_snip}"'

        dur_bad, dur_ratio = AF._duration_mismatch(row)
        if dur_bad:
            fired.append(HEURISTIC_B)
            evidence[HEURISTIC_B] = (
                f"performance-duration ratio {dur_ratio:.2f} (speed-corrected) "
                f">15% off unity"
            )

        if fired:
            hits.append({
                "concert_date": row["concert_date"],
                "lb_a": row["lb_a"],
                "lb_b": row["lb_b"],
                "heuristics": fired,
                "evidence": evidence,
            })

    return fn_rows, hits


def _render(fn_rows: list[dict], hits: list[dict]) -> str:
    total_fn = len(fn_rows)
    count_a = sum(1 for h in hits if HEURISTIC_A in h["heuristics"])
    count_b = sum(1 for h in hits if HEURISTIC_B in h["heuristics"])
    overlap = sum(1 for h in hits
                  if HEURISTIC_A in h["heuristics"] and HEURISTIC_B in h["heuristics"])

    lines = [
        "# FN label-error heuristic census",
        "",
        "Generated by `tools/tapematch/fn_label_census.py`. Report-only: no DB "
        "writes, no `pairs.label_suspect` flagging, no frozen-set label edits. "
        "Reuses `audit_fn.py`'s `_explicit_different_recording` and "
        "`_duration_mismatch` heuristics unmodified, applied to the *full* "
        "corr<0.05 FN population (not a stratified sample).",
        "",
        "## Headline",
        "",
        f"- FN population scanned (corr < {AF.CORR_THRESHOLD}, current committed "
        f"config): **{total_fn}** pairs.",
        f"- Heuristic (a) `{HEURISTIC_A}` hits: **{count_a}**.",
        f"- Heuristic (b) `{HEURISTIC_B}` hits: **{count_b}**.",
        f"- Overlap (both heuristics fire on the same pair): **{overlap}**.",
        f"- Total distinct pairs flagged by either heuristic: **{len(hits)}**.",
        "",
        "| heuristic | hits | % of FN population |",
        "|---|---|---|",
        f"| {HEURISTIC_A} | {count_a} | {count_a / total_fn * 100 if total_fn else 0:.1f}% |",
        f"| {HEURISTIC_B} | {count_b} | {count_b / total_fn * 100 if total_fn else 0:.1f}% |",
        f"| overlap (both) | {overlap} | "
        f"{overlap / total_fn * 100 if total_fn else 0:.1f}% |",
        f"| either (union) | {len(hits)} | "
        f"{len(hits) / total_fn * 100 if total_fn else 0:.1f}% |",
        "",
        "## Flagged pairs",
        "",
        "| date | LB numbers | heuristic | evidence |",
        "|---|---|---|---|",
    ]
    for h in sorted(hits, key=lambda h: (h["concert_date"], h["lb_a"], h["lb_b"])):
        a, b, date = h["lb_a"], h["lb_b"], h["concert_date"]
        for heur in h["heuristics"]:
            lines.append(
                f"| {date} | LB-{a:05d} / LB-{b:05d} | {heur} | {h['evidence'][heur]} |"
            )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    conn = R._connect(R.OBS_DB_PATH)
    try:
        fn_rows, hits = _scan(conn)
    finally:
        conn.close()

    print(_render(fn_rows, hits))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
